// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

let DATABASE_URL = "";
try {
  DATABASE_URL = env("DATABASE_URL");
} catch (e) {
  console.warn(
    "DATABASE_URL environment variable is not set. Please set it to your database connection string.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
